package app

import (
	"fmt"
	"io"
)

// WriteCompletion writes a shell completion script to w. The output matches
// the static scripts in completions/ in the repository.
func WriteCompletion(shell string, w io.Writer) error {
	switch shell {
	case "bash":
		_, err := io.WriteString(w, bashCompletion)
		return err
	case "zsh":
		_, err := io.WriteString(w, zshCompletion)
		return err
	case "fish":
		_, err := io.WriteString(w, fishCompletion)
		return err
	}
	return fmt.Errorf("unsupported shell %q", shell)
}

const bashCompletion = `# bash completion for patchrun (generated by 'patchrun --completion bash')
_patchrun() {
    local cur prev words cword
    _init_completion || return

    local opts="
        --apply --apply-3way
        --save --stdout --json
        --keep --worktree-dir
        --name --git-bin --cwd
        --allow-dirty --fail-on-dirty
        --include-ignored --include --exclude
        --diff --stat --no-stat
        --interactive --no-interactive
        --command-timeout
        --color --no-sidecar
        --list-runs --prune
        --completion
        --quiet --verbose
        --version --help
    "
    case "$prev" in
        --save|--worktree-dir|--git-bin|--cwd) _filedir; return 0 ;;
        --color) COMPREPLY=($(compgen -W "auto always never" -- "$cur")); return 0 ;;
        --completion) COMPREPLY=($(compgen -W "bash zsh fish" -- "$cur")); return 0 ;;
        --include|--exclude|--name|--command-timeout) return 0 ;;
    esac

    local i
    for ((i=1; i<COMP_CWORD; i++)); do
        if [[ "${COMP_WORDS[i]}" == "--" ]]; then
            COMP_WORDS=("${COMP_WORDS[@]:i+1}")
            COMP_CWORD=$((COMP_CWORD - i - 1))
            _command_offset 0
            return 0
        fi
    done

    if [[ "$cur" == --* ]]; then
        COMPREPLY=($(compgen -W "$opts" -- "$cur"))
        return 0
    fi
    COMPREPLY=($(compgen -W "$opts --" -- "$cur"))
}
complete -F _patchrun patchrun
`

const zshCompletion = `#compdef patchrun
# zsh completion for patchrun (generated by 'patchrun --completion zsh')

_patchrun() {
    local -a opts
    opts=(
        '--apply[apply patch to original repo]'
        '--apply-3way[fall back to 3-way merge]'
        '--save=[save patch to path]:patch file:_files'
        '--stdout[print patch to stdout]'
        '--json[machine-readable result JSON]'
        '--keep[keep disposable worktree]'
        '--worktree-dir=[parent for temporary worktrees]:directory:_directories'
        '--name=[label this run]:label:'
        '--allow-dirty[use working tree as baseline]'
        '--fail-on-dirty[refuse dirty tree]'
        '--include-ignored[include ignored files]'
        '*--include=[include only pathspec]:pathspec:_files'
        '*--exclude=[exclude pathspec]:pathspec:_files'
        '--diff[show patch after command]'
        '--stat[show diffstat]'
        '--no-stat[hide diffstat]'
        '--interactive[force menu]'
        '--no-interactive[disable prompts]'
        '--command-timeout=[kill after duration]:duration:'
        '--color=[color mode]:mode:(auto always never)'
        '--no-sidecar[skip .meta.json sidecar]'
        '--git-bin=[git executable]:path:_files'
        '--cwd=[run from path]:path:_directories'
        '--list-runs[list kept worktrees]'
        '--prune[prune patchrun worktrees]'
        '--completion=[print completion]:shell:(bash zsh fish)'
        '--quiet[less output]'
        '--verbose[more output]'
        '--version[print version]'
        '(-h --help)'{-h,--help}'[show help]'
    )
    local idx
    idx=$words[(i)--]
    if (( idx < CURRENT )); then
        words=( "${(@)words[idx+1,$#words]}" )
        (( CURRENT -= idx ))
        _normal
        return
    fi
    _arguments -s -S "${opts[@]}" '*::cmd:->cmd'
    case $state in cmd) _normal ;; esac
}
_patchrun "$@"
`

const fishCompletion = `# fish completion for patchrun (generated by 'patchrun --completion fish')

function __patchrun_after_separator
    set -l tokens (commandline -opc)
    for tok in $tokens
        if test "$tok" = "--"
            return 0
        end
    end
    return 1
end

set -l n 'not __patchrun_after_separator'
complete -c patchrun -n "$n" -l apply
complete -c patchrun -n "$n" -l apply-3way
complete -c patchrun -n "$n" -l save -r
complete -c patchrun -n "$n" -l stdout
complete -c patchrun -n "$n" -l json
complete -c patchrun -n "$n" -l keep
complete -c patchrun -n "$n" -l worktree-dir -r
complete -c patchrun -n "$n" -l name -r
complete -c patchrun -n "$n" -l allow-dirty
complete -c patchrun -n "$n" -l fail-on-dirty
complete -c patchrun -n "$n" -l include-ignored
complete -c patchrun -n "$n" -l include -r
complete -c patchrun -n "$n" -l exclude -r
complete -c patchrun -n "$n" -l diff
complete -c patchrun -n "$n" -l stat
complete -c patchrun -n "$n" -l no-stat
complete -c patchrun -n "$n" -l interactive
complete -c patchrun -n "$n" -l no-interactive
complete -c patchrun -n "$n" -l command-timeout -r
complete -c patchrun -n "$n" -l color -xa 'auto always never'
complete -c patchrun -n "$n" -l no-sidecar
complete -c patchrun -n "$n" -l git-bin -r
complete -c patchrun -n "$n" -l cwd -r
complete -c patchrun -n "$n" -l list-runs
complete -c patchrun -n "$n" -l prune
complete -c patchrun -n "$n" -l completion -xa 'bash zsh fish'
complete -c patchrun -n "$n" -l quiet
complete -c patchrun -n "$n" -l verbose
complete -c patchrun -n "$n" -l version
complete -c patchrun -n "$n" -s h -l help
`
